# 1. What is a Python library? Why do we use Python libraries?
Ans:- Python library is a collection of functions and classes which can be used by python users to make the development easier.
    Python has many inbuilt libraries which are used for different development purposes like numpy, pandas, matplotlib, etc.

# 2. What is the difference between Numpy array and List?
Ans:- The core building of numpy array is built on top of c++, that's why it has very fast computation power. 
    Whereas List has slower computation power than numpy.

# 3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [1]:
import numpy as np
arr1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [2]:
arr1.shape

(3, 4)

In [3]:
arr1.size

12

In [4]:
arr1.ndim

2

# 4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [5]:
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
arr2[0]

array([1, 2, 3, 4])

# 5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [7]:
arr3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
arr3[-1, -1]

12

In [9]:
arr3[2, 3]

12

# 6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [10]:
arr4 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
arr4[:, 1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [12]:
arr5 = np.random.rand(3,3)
arr5

array([[0.57833259, 0.89290092, 0.71283473],
       [0.03477099, 0.86920469, 0.69130947],
       [0.47401633, 0.60089448, 0.17846642]])

# 8. Describe the difference between np.random.rand and np.random.randint?
Ans:- np.random.rand() function takes size as argument and returns random values between 0 and 1 .
    whereas, np.random.randint() function takes the range of values and size of the array and then returns according to the given arguments.

# 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [13]:
arr6 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
arr6 = np.expand_dims(arr6, axis=1)
arr6

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

# 10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [15]:
arr7 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr7

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
arr7.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# 11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1:-

In [45]:
matA2 = np.mat([[1, 2, 3],[5, 6, 7],[9, 10, 11]])
matA2

matrix([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]])

In [46]:
matB2 = np.mat([[1, 2, 3], [5, 6, 7],[9, 10, 11]])
matB2

matrix([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]])

In [47]:
# i)Ans:-
np.multiply(matA2, matB2)

matrix([[  1,   4,   9],
        [ 25,  36,  49],
        [ 81, 100, 121]])

In [48]:
# ii)Ans:- Matrix multiplication is not possible for given matrices. so, I have made the both matrices 3X3.
np.dot(matA2, matB2)

matrix([[ 38,  44,  50],
        [ 98, 116, 134],
        [158, 188, 218]])

In [49]:
# iii)Ans:- Addition
matA2 + matB2

matrix([[ 2,  4,  6],
        [10, 12, 14],
        [18, 20, 22]])

In [50]:
# iv)Ans:- Subtract
matB2 - matA2

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [51]:
# v)Ans:- Division
matB2 // matA2

matrix([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

# 12. Which function in Numpy can be used to swap the byte order of an array?
Ans:- byteswap() function is used to swap the byte order of an array.

# 13. What is the significance of the np.linalg.inv function?
Ans:- the significance of the np.linalg.inv function is to compute the multiplicative inverse of a sqrare matrix.

# 14. What does the np.reshape function do, and how is it used?
Ans:- np.reshape() reshapes the function according the given shape as argument.

In [56]:
arr = np.asarray([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
np.reshape(arr, (1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# 15. What is broadcasting in Numpy?
Ans:- Broadcasting is the mechanism to perform element wise operation to an array.

In [58]:
arr + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])